Backend: Vivado
Board: null
ClockPeriod: 40
HLSConfig:
  LayerName:
    Hidden_layer_2:
      Precision:
        bias: ap_fixed<16,6>
        result: ap_fixed<16,6>
        weight: ap_fixed<16,6>
      ReuseFactor: 1
    Hidden_layer_2_relu:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
    Hidden_layer_3:
      Precision:
        bias: ap_fixed<16,6>
        result: ap_fixed<16,6>
        weight: ap_fixed<16,6>
      ReuseFactor: 1
    Hidden_layer_3_relu:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
    Input_layer:
      Precision:
        result: ap_int<2>
    Output_layer:
      Precision:
        bias: ap_fixed<16,6>
        result: ap_fixed<16,6>
        weight: ap_fixed<16,6>
      ReuseFactor: 1
    Output_layer_softmax:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      table_size: 1024
      table_t: ap_fixed<18,8>
    batch_normalization_1:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 1
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Resource
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'test_prj/keras_model.h5'
OutputDir: test_prj
OutputPredictions: null
ProjectName: myproject
Stamp: A9D5dCB6
XilinxPart: xc7a35tcpg236-1
